Give nicer error to users when loading modules from different toolchains
hpcugent/Lmod-UGent pull request #11
Opened 2016-09-07 14:05 UTC by wpoely86

Fixes #9 

With this:
```
$ ml zlib/1.2.8-intel-2014b
$ ml ncurses
Lmod has detected the following error:  You can not load modules using different toolchains. A different version of the 'intel' module is already loaded (see output of 'ml').
You should load another 'ncurses' module for that is compatible with the currently loaded version of 'intel'. Use 'ml spider ncurses' to get an overview of the available versions. 

While processing the following module(s):
    Module fullname          Module Filename
    ---------------          ---------------
    ncurses/6.0-intel-2016a  /apps/gent/SL6/westmere/modules/all/ncurses/6.0-intel-2016a

If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

```

2016-09-08 07:11 UTC, boegel commented on SitePackage.lua
> +        s[#s+1] = buildMsg(twidth, label, "You can not load modules using different toolchains.",
@wpoely86 this error will not only pop up when two versions of the same toolchain but different version is loaded, but also for other conflicts on module name, right?

For example, if someone loads A which depends on Python 2.7.12, and then loads B which depends on Python 3.5.2?

So, we should not mention 'toolchian' at all in the error message, and only talk about 'module name' and 'module version'?

2016-09-15 15:10 UTC, wpoely86 commented
What does this do:
```
$ ml zlib/1.2.8-intel-2015a
$ ml zlib/1.2.8-intel-2016a
Lmod has detected the following error:  A different version of the 'zlib' module is already loaded (see output of 'ml'). 



If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

$ ml ncurses/6.0-intel-2016a
Lmod has detected the following error:  A different version of the 'intel' module is already loaded (see output of 'ml'). You should load another 'ncurses' module for that is compatible with the currently loaded version of
'intel'. Use 'ml spider ncurses' to get an overview of the available versions. 

While processing the following module(s):
    Module fullname          Module Filename
    ---------------          ---------------
    ncurses/6.0-intel-2016a  /apps/gent/SL6/westmere/modules/all/ncurses/6.0-intel-2016a

If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

```

2016-09-15 15:13 UTC, boegel commented on SitePackage.lua
> +            errmsg[#errmsg+1] = "an overview of the available versions."
@wpoely86 start every sentence on a new line, to try and make sure people will actually *read*

2016-09-15 15:14 UTC, wpoely86 commented on SitePackage.lua
> +            errmsg[#errmsg+1] = "an overview of the available versions."
The terminal does the wrapping, not me.

2016-09-15 15:29 UTC, boegel commented on SitePackage.lua
> +            errmsg[#errmsg+1] = "an overview of the available versions."
I know the terminal wraps, but starting each new sentence on a new line will significantly improve the readability of the error message. Try it, and compare.

2016-09-15 15:35 UTC, wpoely86 commented
Now:
```
$ ml GSL
Lmod has detected the following error:  A different version of the 'intel' module is already loaded (see output of 'ml').
You should load another 'GSL' module for that is compatible with the currently loaded version of 'intel'.
Use 'ml spider GSL' to get an overview of the available versions. 

While processing the following module(s):
    Module fullname      Module Filename
    ---------------      ---------------
    GSL/2.1-intel-2016b  /apps/gent/SL6/sandybridge/modules/all/GSL/2.1-intel-2016b

If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

```

2016-09-16 09:34 UTC, boegel commented
@wpoely86 looks good, but can we avoid the excessive vertical whitespace when loading a module that is already loaded?

```
[11:30:46] vsc40023@test2802:~/vsc-testing/module $ ml Python/2.7.9-intel-2015a 
[11:30:56] vsc40023@test2802:~/vsc-testing/module $ ml 

Currently Loaded Modules:
  1) cluster/.banette (S)   3) icc/2015.1.133-GCC-4.9.2     5) iccifort/2015.1.133-GCC-4.9.2                  7) iimpi/7.2.3-GCC-4.9.2                   9) intel/2015a              11) zlib/1.2.8-intel-2015a       13) ncurses/5.9-intel-2015a
  2) GCC/4.9.2              4) ifort/2015.1.133-GCC-4.9.2   6) impi/5.0.2.044-iccifort-2015.1.133-GCC-4.9.2   8) imkl/11.2.1.133-iimpi-7.2.3-GCC-4.9.2  10) bzip2/1.0.6-intel-2015a  12) libreadline/6.3-intel-2015a  14) Python/2.7.9-intel-2015a

  Where:
   S:  Module is Sticky, requires --force to unload or purge
[11:30:58] vsc40023@test2802:~/vsc-testing/module $ ml Python/3.4.3-intel-2015a
Lmod has detected the following error:  A different version of the 'Python' module is already loaded (see output of 'ml'). 



If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

[11:31:04] vsc40023@test2802:~/vsc-testing/module $ ml matplotlib/1.4.3-intel-2015a-Python-3.4.3 
Lmod has detected the following error:  A different version of the 'Python' module is already loaded (see output of 'ml').
You should load another 'matplotlib' module for that is compatible with the currently loaded version of 'Python'.
Use 'ml spider matplotlib' to get an overview of the available versions. 

While processing the following module(s):
    Module fullname                            Module Filename
    ---------------                            ---------------
    matplotlib/1.4.3-intel-2015a-Python-3.4.3  /apps/gent/SL6/westmere/modules/all/matplotlib/1.4.3-intel-2015a-Python-3.4.3

If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

[11:32:01] vsc40023@test2802:~/vsc-testing/module $ 
```

2016-09-16 13:09 UTC, boegel commented on Lmod-UGent.spec
> +Version:        6.5.11
@wpoely86 please bump to 6.5.12 (cfr. https://github.com/TACC/Lmod/issues/162)

2016-09-16 13:09 UTC, boegel requested changes

2016-09-16 13:53 UTC, boegel commented
@wpoely86 ping on avoiding the excessive vertical whitespace?

2016-09-27 14:10 UTC, wpoely86 commented
Now:
```
$ ml zlib/1.2.8-intel-2015a
$ ml zlib/1.2.8-intel-2015b
Lmod has detected the following error:  A different version of the 'zlib' module is already loaded (see output of 'ml'). 

If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

$ ml ncurses/5.9-intel-2014b
Lmod has detected the following error:  A different version of the 'intel' module is already loaded (see output of 'ml').
You should load another 'ncurses' module for that is compatible with the currently loaded version of 'intel'.
Use 'ml spider ncurses' to get an overview of the available versions. 
While processing the following module(s):
    Module fullname          Module Filename
    ---------------          ---------------
    ncurses/5.9-intel-2014b  /apps/gent/SL6/westmere/modules/all/ncurses/5.9-intel-2014b

If you don't understand the warning or error, contact the helpdesk at hpc@ugent.be

```

2016-09-27 14:13 UTC, boegel approved these changes

2016-09-27 14:15 UTC, boegel commented
,gtm

2016-09-27 14:15 UTC, merged